theme: jekyll-theme-tactile
include_markdown:
  dir: docs   # Base directory of template markdown
  verbose : true          # If you want to check the path of markdown that use <!-- md --> tag , please set the true.
